package com.monero.bitcoin;

// GENERATED FILE -- do not edit by hand.
// Source: ../../constants/create_bitcoin_address.json
// Regenerated by constants/gen_java_constants.py (see build.xml's gen-constants target).
final class Constants {
    private Constants() {}

    static final byte INS_GENERATE_ENTROPY = (byte) 0x30;
}
