"""
Regenerates Java-side build artifacts from one of this directory's JSON
constants files, so an applet and its Python client share one source of
truth instead of each hand-maintaining a duplicate of the same hex values.

JavaCard applets can't read JSON (or any file) at runtime -- no filesystem,
no JSON parser in the JavaCard API, and the card is a separate device from
wherever this script runs. So instead this runs at build time, before
javac/ant-javacard ever sees the sources: byte/short-typed values become a
generated Constants.java the applet imports as compiled-in constants, and
AID-shaped values become a .properties file build.xml loads with
<property file=...> for ant-javacard's aid="..." attributes.

Run by build.xml's gen-constants target -- not meant to be run standalone,
though it's safe to.

Usage: gen_java_constants.py <json_file> <java_package> <java_output> <properties_output>
"""
import json
import sys


def main():
    json_path, package, java_output, properties_output = sys.argv[1:5]
    with open(json_path) as f:
        data = json.load(f)

    properties_lines = []
    java_fields = []
    for key, value in data.items():
        if key == "aid":
            properties_lines.append(f"aid={value}")
            continue
        field = key.upper()
        if isinstance(value, str) and value.lower().startswith("0x"):
            java_fields.append(f"    static final byte {field} = (byte) {value};")
        elif isinstance(value, int):
            java_fields.append(f"    static final short {field} = (short) {value};")
        else:
            raise ValueError(f"Don't know how to emit a Java constant for {key!r} = {value!r}")

    with open(properties_output, "w", newline="\n") as f:
        f.write("\n".join(properties_lines) + "\n")

    java_lines = [
        f"package {package};",
        "",
        "// GENERATED FILE -- do not edit by hand.",
        f"// Source: {json_path.replace(chr(92), '/')}",
        "// Regenerated by constants/gen_java_constants.py (see build.xml's gen-constants target).",
        "final class Constants {",
        "    private Constants() {}",
        "",
        *java_fields,
        "}",
        "",
    ]
    with open(java_output, "w", newline="\n") as f:
        f.write("\n".join(java_lines))

    print(f"Wrote {properties_output} and {java_output}")


if __name__ == "__main__":
    main()
